### ISSUE TITLE
download_and_index.py errors

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#21]
python scripts/download_and_index.py --apikey XXXX

Traceback (most recent call last):
  File "scripts/download_and_index.py", line 77, in <module>
    main(args)
  File "scripts/download_and_index.py", line 8, in main
    SETTINGS = json.load(open("config.json", "rb"))
  File "\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 16 column 3 (char 374)

**Comment by Medwynd** [comment]
Had a bad merge in config.json and was missing a comma between fields
