### ISSUE TITLE
Error when running scripts/download_and_index.py

### ISSUE THREAD

**Issue by lajlev** [EmilStenstrom/mybgg#22]
```
Python 3.7.0


python3 scripts/download_and_index.py --apikey MYKEY

Traceback (most recent call last):
  File "scripts/download_and_index.py", line 3, in <module>
    from mybgg.downloader import Downloader
  File "/Users/lajlev/Sites/mybgg/scripts/mybgg/downloader.py", line 1, in <module>
    from mybgg.bgg_client import BGGClient
  File "/Users/lajlev/Sites/mybgg/scripts/mybgg/bgg_client.py", line 5, in <module>
    import declxml as xml
ModuleNotFoundError: No module named 'declxml'
```

Any clue?

**Comment by EmilStenstrom** [comment]
Hi!

Sounds like you haven't installed one of the dependencies. declxml is listed here: https://github.com/EmilStenstrom/mybgg/blob/master/scripts/requirements.txt

Should be as simple as following step 3 in the getting started guide:

```
pip install -r scripts/requirements.txt
```

**Comment by lajlev** [comment]
Last solution worked
