### ISSUE TITLE
Issue pulling down games from bgg

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#29]
**Traceback**
Traceback (most recent call last):
  File "scripts/download_and_index.py", line 78, in <module>
    main(args)
  File "scripts/download_and_index.py", line 17, in main
    extra_params=SETTINGS["boardgamegeek"]["extra_params"],
  File "D:\mybggnew\mybgg\scripts\mybgg\downloader.py", line 36, in collection
    game_list_data = self.client.game_list([game_in_collection["id"] for game_in_collection in collection_data])
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 43, in game_list
    games += self._games_list_to_games(data)
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 235, in _games_list_to_games
    games = xml.parse_from_string(game_processor, data)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 311, in parse_from_string
    return root_processor.parse_at_root(root, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 972, in parse_at_root
    parsed_dict = self.parse_at_element(dict_element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 956, in parse_at_element
    parsed_dict[child.alias] = child.parse_from_parent(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 823, in parse_from_parent
    return self._parse(item_iter, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 880, in _parse
    parsed_array.append(self._item_processor.parse_at_element(item, state))
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1085, in parse_at_element
    xml_value = self._processor.parse_at_element(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 956, in parse_at_element
    parsed_dict[child.alias] = child.parse_from_parent(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1227, in parse_from_parent
    MissingValue, 'Missing required element "{}"'.format(self.element_path)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1369, in raise_error
    raise exception_type(error_message)
declxml.MissingValue: Missing required element "statistics/ratings/ranks/rank[@friendlyname='Board Game Rank']" at items/item[16]/statistics/ratings/ranks/rank[@friendlyname='Board Game Rank']

**Traceback with debug flag**
DEBUG:mybgg.bgg_client:Successfully parsed: Nothing Personal Expansion Pack #3: Movies and TV (id: 181500).
DEBUG:mybgg.bgg_client:Successfully parsed: Nothing Personal: Associates (id: 158202).
DEBUG:mybgg.bgg_client:Successfully parsed: Nothing Personal: Power & Influence (id: 157488).
Traceback (most recent call last):
  File "scripts/download_and_index.py", line 78, in <module>
    main(args)
  File "scripts/download_and_index.py", line 17, in main
    extra_params=SETTINGS["boardgamegeek"]["extra_params"],
  File "D:\mybggnew\mybgg\scripts\mybgg\downloader.py", line 36, in collection
    game_list_data = self.client.game_list([game_in_collection["id"] for game_in_collection in collection_data])
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 43, in game_list
    games += self._games_list_to_games(data)
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 235, in _games_list_to_games
    games = xml.parse_from_string(game_processor, data)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 311, in parse_from_string
    return root_processor.parse_at_root(root, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 972, in parse_at_root
    parsed_dict = self.parse_at_element(dict_element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 956, in parse_at_element
    parsed_dict[child.alias] = child.parse_from_parent(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 823, in parse_from_parent
    return self._parse(item_iter, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 880, in _parse
    parsed_array.append(self._item_processor.parse_at_element(item, state))
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1085, in parse_at_element
    xml_value = self._processor.parse_at_element(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 956, in parse_at_element
    parsed_dict[child.alias] = child.parse_from_parent(element, state)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1227, in parse_from_parent
    MissingValue, 'Missing required element "{}"'.format(self.element_path)
  File "E:\Python37-32\lib\site-packages\declxml.py", line 1369, in raise_error
    raise exception_type(error_message)
declxml.MissingValue: Missing required element "statistics/ratings/ranks/rank[@friendlyname='Board Game Rank']" at items/item[15]/statistics/ratings/ranks/rank[@friendlyname='Board Game Rank']

**Comment by Medwynd** [comment]
Note that I recently added the entry for this expansion and it was just approved a few hours ago.  https://boardgamegeek.com/boardgameexpansion/287920/nothing-personal-scenes-crime

**Comment by EmilStenstrom** [comment]
Hi! Your hunch was correct: That game was missing a whole lot of information, and my code didn't account for that. It's now fixed and should work with the latest version.

Hope you appreciate the work!

**Comment by Medwynd** [comment]
Awesome, thanks for the fix and it is working fine for me again.  I've been regularly recommending this as a solution for people over some of the alternatives out there since I think this is the cleanest and most appealing solution out there :)

**Comment by EmilStenstrom** [comment]
@Medwynd Happy to hear! :) 🎲
