### ISSUE TITLE
ModuleNotFoundError: No module named 'declxml'

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#41]
Probably some sort of configuration issue on my part.  I havent updated my games in a while.  I pulled the latest and declxml is in the requirements.txt file.
`declxml==1.1.3            # via -r scripts/requirements.in`

Installing the requirements says decl.xml is up to date
`Requirement already satisfied: declxml==1.1.3 in e:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from -r scripts/requirements.txt (line 11))`

```
Traceback (most recent call last):
  File "e:\Users\User\Documents\mybgg-git\mybgg\scripts\download_and_index.py", line 3, in <module>
    from mybgg.downloader import Downloader
  File "e:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\downloader.py", line 1, in <module>
    from mybgg.bgg_client import BGGClient
  File "e:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 5, in <module>
    import declxml as xml
ModuleNotFoundError: No module named 'declxml'
```

Not sure what I am missing here or how to get it to find the package

**Comment by EmilStenstrom** [comment]
Hi! You should be able to install the requirements with `pip install -r scripts/requirements.txt` -- does that work?

**Comment by EmilStenstrom** [comment]
Also, if you update to the latest version, there is an option to automatically sync you games every hour using GitHub Actions.

**Comment by Medwynd** [comment]
> Hi! You should be able to install the requirements with `pip install -r scripts/requirements.txt` -- does that work?

Sorry for the lack of clarity, that is what I meant by "Installing the requirements says decl.xml is up to date".

Using the command you listed says it is installed properly and up to date.

**Comment by EmilStenstrom** [comment]
Thanks. That should mean that the command you run does not find the packages you installed with pip. What command are you running the returns the above error?

**Comment by Medwynd** [comment]
Ok I seem to have gotten the command to work, I think I was leaving the "python" off the front of it and just using 
"scripts/download_and_index.py --apikey XXXXXX"

Now I get this error:
BGGException: BGG returned status code 429
```
Traceback (most recent call last):
  File "scripts/download_and_index.py", line 77, in <module>
    main(args)
  File "scripts/download_and_index.py", line 17, in main
    extra_params=SETTINGS["boardgamegeek"]["extra_params"],
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\downloader.py", line 34, in collection
    **extra_params,
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 26, in collection
    data = self._make_request("/collection?version=1", params)
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  [Previous line repeated 2 more times]
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\bgg_client.py", line 94, in _make_request
    f"BGG returned status code {response.status_code} when "
mybgg.bgg_client.BGGException: BGG returned status code 429
```

**Comment by Medwynd** [comment]
I ran it again and the second time seemed to get further but now I get:

```
Traceback (most recent call last):
  File "scripts/download_and_index.py", line 77, in <module>
    main(args)
  File "scripts/download_and_index.py", line 34, in main
    indexer.add_objects(collection)
  File "E:\Users\User\Documents\mybgg-git\mybgg\scripts\mybgg\indexer.py", line 184, in add_objects
    self.index.save_objects(games)
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\search_index.py", line 72, in save_objects
    response = self._chunk("updateObject", objects, request_options)
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\search_index.py", line 527, in _chunk
    raw_responses.append(self._raw_batch(requests, request_options))
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\search_index.py", line 538, in _raw_batch
    request_options,
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\http\transporter.py", line 35, in write
    return self.request(verb, hosts, path, data, request_options, timeout)
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\http\transporter.py", line 72, in request
    return self.retry(hosts, request, relative_url)
  File "E:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\algoliasearch\http\transporter.py", line 92, in retry
    raise RequestException(content, response.status_code)
algoliasearch.exceptions.RequestException: Record at the position 354 objectID=bgg146791 is too big size=11931 bytes. Contact us if you need an extended quota
```

**Comment by Medwynd** [comment]
https://boardgamegeek.com/boardgame/146791/shadows-brimstone-city-ancients
146791 is Shadow of Brimstone, perhaps it cant handle that many expansions?

**Comment by EmilStenstrom** [comment]
You are getting the strangest error messages :)

The 429 is just because BGG is very flaky. Seems 50% of requests ends up working with them.

The "Record too big" is new for me. Makes sense that too many extensions makes the record too big for algolia. Might be something that can be done to make the records smaller... hmm...

**Comment by Medwynd** [comment]
> The "Record too big" is new for me. Makes sense that too many extensions makes the record too big for algolia. Might be something that can be done to make the records smaller... hmm...

Can it possibly just truncate the record for now until a proper solution is come up with?  I think this blocks any updates of the collection.

**Comment by EmilStenstrom** [comment]
Yes, you could try that. Or removing it from your collection temporarily.

**Comment by Medwynd** [comment]
Since these all share expansions I had to remove both of these to get the upload to work
https://boardgamegeek.com/boardgame/146791/shadows-brimstone-city-ancients
https://boardgamegeek.com/boardgame/150997/shadows-brimstone-swamps-death

**Comment by EmilStenstrom** [comment]
Ok, so now I've took some of my free time to look at this.

* I've added a linebreaks in the docs as you suggested. Hoping this might save someone in the future.
* I'm now capturing the 429 error, which means we are making requests to BGG too fast. When this happens, the script will pause 30 seconds and then continue. Adding --debug to the commands prints an info message when this happens.
* To make sure all Shadows of Brimstone expansions can be added, I've removed the game name from the beginning of the expansion name. The only place it shows up is in the expansion list, and it's fairly redudant there, so I think this is a nice tradeoff. I've tried adding all Brimstone expansions, and things seem to work well.

**Comment by EmilStenstrom** [comment]
ping @Medwynd

**Comment by Medwynd** [comment]
Was able to successfully pass and upload.

> When this happens, the script will pause 30 seconds and then continue.

This did not happen for me, the script just ended.

```
Traceback (most recent call last):
  File "scripts/download_and_index.py", line 77, in <module>
    main(args)
  File "scripts/download_and_index.py", line 17, in main
    extra_params=SETTINGS["boardgamegeek"]["extra_params"],
  File "D:\mybggnew\mybgg\scripts\mybgg\downloader.py", line 34, in collection
    **extra_params,
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 26, in collection
    data = self._make_request("/collection?version=1", params)
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 85, in _make_request
    return self._make_request(url, params=params, tries=tries + 1)
  [Previous line repeated 2 more times]
  File "D:\mybggnew\mybgg\scripts\mybgg\bgg_client.py", line 101, in _make_request
    f"BGG returned status code {response.status_code} when requesting {response.url}"
mybgg.bgg_client.BGGException: BGG returned status code 429 when requesting 
```

**Comment by EmilStenstrom** [comment]
Oh come on. A little thanks for me fixing your problem for you?

**Comment by Medwynd** [comment]
> 
> 
> Oh come on. A little thanks for me fixing your problem for you?

Much appreciated for the assist! Sorry not used to leaving anything but the facts in bug reports, force of habit.

**Comment by EmilStenstrom** [comment]
@Medwynd As a open source maintainer, thanks is the only thing you get for toiling away over the years. Thanks!
