### ISSUE TITLE
Issue with adding game to collection, objectID=bgg150997 is too big size=10763/10000 bytes

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#64]
My guess is it has too many expansions
https://boardgamegeek.com/boardgame/150997/shadows-brimstone-swamps-death

Traceback (most recent call last):
  File "E:\mybgg\scripts\download_and_index.py", line 77, in <module>
    main(args)
  File "E:\mybgg\scripts\download_and_index.py", line 34, in main
    indexer.add_objects(collection)
  File "E:\mybgg\scripts\mybgg\indexer.py", line 226, in add_objects
    self.index.save_objects(games)
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\search_index.py", line 72, in save_objects
    response = self._chunk("updateObject", objects, request_options)
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\search_index.py", line 527, in _chunk
    raw_responses.append(self._raw_batch(requests, request_options))
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\search_index.py", line 534, in _raw_batch
    return self._transporter.write(
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\http\transporter.py", line 35, in write
    return self.request(verb, hosts, path, data, request_options, timeout)
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\http\transporter.py", line 72, in request
    return self.retry(hosts, request, relative_url)
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\http\transporter.py", line 92, in retry
    raise RequestException(content, response.status_code)
algoliasearch.exceptions.RequestException: Record at the position 401 objectID=bgg150997 is too big size=10763/10000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits

**Comment by EmilStenstrom** [comment]
Hi! This is now fixed by only showing 10 expansions, and then supplying a link to bgg where all expansions (given that they contain the original game's name as a prefix) are listed. Try running the latest version. Hope this fixes your problem.

As I've said before, I would appreciate you asking nicely when posting reports like this. A stranger on the other side of the world is doing free work for you, without getting anything in return.

**Comment by Medwynd** [comment]
Thanks appreciate the change, I'll give it a shot.  I do appreciate your work and not sure why I'm the only one you scold.  I was just trying to not clutter up the issue report with fluff.

**Comment by Medwynd** [comment]
The change didnt work for me, I recloned the project to make sure I had the latest and checked indexer.py and it does have the code under 
`# Algolia has a limit of 10kb per item, so remove unnessesary data from expansions`

but still has the error in it while indexing
  File "E:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\algoliasearch\http\transporter.py", line 92, in retry
    raise RequestException(content, response.status_code)
algoliasearch.exceptions.RequestException: Record at the position 401 objectID=bgg150997 is too big size=10763/10000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits

Let me know if there's any other logging I can turn on that may help assist you with it.  Thanks again!

**Comment by EmilStenstrom** [comment]
Happy it worked out!
