### ISSUE TITLE
 Expecting property name enclosed in double quotes: line 3 column 27 (char 45)

### ISSUE THREAD

**Issue by cryyogenic** [EmilStenstrom/mybgg#78]
Keep getting the following error when trying to download games and send them to algolia

Traceback (most recent call last):
  File "C:\Users\Ryan\mybgg-master\scripts\download_and_index.py", line 77, in <module>
    main(args)
  File "C:\Users\Ryan\mybgg-master\scripts\download_and_index.py", line 8, in main
    SETTINGS = json.load(open("config.json", "rb"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 27 (char 45)

**Comment by EmilStenstrom** [comment]
@cryyogenic Hi! I would need to see the actual JSON to understand what the problem is. Could you run the download command again, this time adding --debug to the end of the command? And then post the resulting output here.

**Comment by EmilStenstrom** [comment]
@cryyogenic The problem is that your config file has comments in it. JSON does not support comments, so if you remove them everything will work as you would expect: https://github.com/cryyogenic/mybgg/blob/master/config.json

**Comment by cryyogenic** [comment]
Thanks Emil! That worked! And sorry for not getting back to you sooner. I now get a success message when running:

Imported 116 games and 35 expansions from boardgamegeek.
Indexed 25 of 116 games...
Indexed 50 of 116 games...
Indexed 75 of 116 games...
Indexed 100 of 116 games...
Indexed 116 games and 35 expansions in algolia, and removed everything else.

HOWEVER, the webpage shows up blank when I go there, any thoughts as to why?

https://cryyogenic.github.io/mybgg/

**Comment by cryyogenic** [comment]
Nevermind, working now! Probably just took a few minutes to update.

Thank you for all of your help!

**Comment by EmilStenstrom** [comment]
@cryyogenic Thank you for sponsoring! :)
