### ISSUE TITLE
API limit changes

### ISSUE THREAD

**Issue by andypiper** [EmilStenstrom/mybgg#81]
I noticed that the background tasks to update my index were throwing a lot of errors, and in fact beyond the first page of results it now returns the BGG TOS page. I then checked the BGG forums and noticed that [they have changed the API behaviour](https://boardgamegeek.com/thread/3330409/article/44543866#44543866). 

Not sure how to approach this. There's almost certainly no need to run the GitHub Action to refresh the data very often, so it might be possible to update the logic to segment the calls to update the collection over a period of time.

**Comment by Kornstalx** [comment]
Wow that change is... most unfortunate.
I went to update my collection today and ran into the same problems. Looks like timeouts are back on the menu.

**Comment by EmilStenstrom** [comment]
@andypiper @Kornstalx I've updated the library to do calls for 20 games per call instead of 100 like it was before. For me, it works using the latest version. Will turn the GitHub Action on that called their API hourly and report back if there's any issues.

A separate change is that we now have exponential back-off for any errors on their part, so if we encounter any problems we'll just wait progressively longer and then try again. Should work with whatever strange timeout limits they decide to impose. 

Please try out the new code and report back.

**Comment by nraw** [comment]
I guess we don't know yet what the timeout limits will be?

**Comment by EmilStenstrom** [comment]
No, but I feel certain that trying 1, 2, 4, 8, 16, 32, 64, ... seconds delay incrementally will work, no matter the delay.

**Comment by andypiper** [comment]
I've updated the code, but I'm seeing this happen:

```
DEBUG:urllib3.connectionpool:[https://www.boardgamegeek.com:443](https://www.boardgamegeek.com/) "GET /xmlapi2/thing/?stats=1&id=340281,173346,309116,202976,264647,295948,6541,260789,261831,321299,299571,191925,219513,264238,54137,211534,18803,46007,308989,822,291515,322457,175653,195771,211023,2993,5405,31784,169392,38431,118614,123905,248979,118617,308636,324940,2591,18836,291517,50381,181423,188497,188496,199399,214020,168292,147209,188498,273825,178900,224198,224037,196526,231019,147151,2719,131357,41833,225694,169654,235365,275451,324413,370591,172225,312667,204053,260214,341164,232918,322070,240004,240004,163170,168278,65244,235252,348732,2655,30323,139666,193621,116609,256831,355899,147194,268936,2838,236191,129622,240529,244992,229537,319706,328569,299249,282765,230251,165347,181370 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Resetting dropped connection: boardgamegeek.com
DEBUG:urllib3.connectionpool:https://boardgamegeek.com:443 "GET /xmlapi2/thing/?stats=1&id=340281,173346,309116,202976,264647,295948,6541,260789,261831,321299,299571,191925,219513,264238,54137,211534,18803,46007,308989,822,291515,322457,175653,195771,211023,2993,5405,31784,169392,38431,118614,123905,248979,118617,308636,324940,2591,18836,291517,50381,181423,188497,188496,199399,214020,168292,147209,188498,273825,178900,224198,224037,196526,231019,147151,2719,131357,41833,225694,169654,235365,275451,324413,370591,172225,312667,204053,260214,341164,232918,322070,240004,240004,163170,168278,65244,[2352](https://github.com/andypiper/mybgg/actions/runs/10168973984/job/28222231088#step:6:2353)52,348732,2655,30323,139666,193621,116609,256831,355899,147194,268936,2838,236191,129622,240529,244992,229537,319706,328569,299249,282765,230251,165347,181370 HTTP/1.1" 400 30
Traceback (most recent call last):
  File "/home/runner/work/mybgg/mybgg/scripts/mybgg/bgg_client.py", line 97, in _make_request
    response.raise_for_status()  # This will raise an exception for 4xx and 5xx status codes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://boardgamegeek.com/xmlapi2/thing/?stats=1&id=340281,173346,309116,202976,264647,295948,6541,260789,261831,321299,299571,191925,219513,264238,54137,211534,18803,46007,308989,822,291515,322457,175653,195771,211023,2993,5405,31784,169392,38431,118614,123905,248979,118617,308636,324940,2591,18836,291517,50381,181423,188497,188496,199399,214020,168292,147209,188498,273825,178900,224198,224037,196526,231019,147151,2719,131357,41833,225694,169654,[2353](https://github.com/andypiper/mybgg/actions/runs/10168973984/job/28222231088#step:6:2354)65,275451,324413,370591,172225,312667,204053,260214,341164,232918,322070,240004,240004,163170,168278,65244,235252,348732,2655,30323,139666,193621,116609,256831,355899,147194,268936,2838,236191,129622,240529,244992,229537,319706,328569,299249,282765,230251,165347,181370
```

**Comment by EmilStenstrom** [comment]
Happy you fixed it @andypiper! (got a notification of a post that you might have deleted?)

**Comment by andypiper** [comment]
Yes, seems OK now (I re-ran an action which failed, but I guess the old code was still cached; Actions run again now)
